#!/usr/bin/env bash
set -euo pipefail

COUNT=5
PREFIX="acc"
BASE_DIR="${CODEX_ACCOUNTS_DIR:-$HOME/.codex-accounts}"
RC_FILE=""
WRITE_RC=1
COPY_SHARED=0

BEGIN_MARKER="# >>> multiple-codex-accounts >>>"
END_MARKER="# <<< multiple-codex-accounts <<<"

usage() {
  cat <<'EOF'
Install multiple Codex CLI account slots.

USAGE
  ./install.sh [options]

OPTIONS
  -n, --count <num>       Number of account slots to create. Default: 5
  -p, --prefix <name>     Slot prefix. Default: acc
  -d, --dir <path>        Account directory. Default: ~/.codex-accounts
      --rc <path>         Shell rc file to update. Default: auto-detect
      --no-rc             Only create directories; do not edit shell rc
      --copy-shared       Copy safe shared files from ~/.codex into every slot
  -h, --help              Show this help

EXAMPLES
  ./install.sh
  ./install.sh --count 10
  ./install.sh --dir "$HOME/.codex-accounts" --rc "$HOME/.zshrc"
EOF
}

die() {
  echo "[ERR] $*" >&2
  exit 1
}

note() {
  echo "[*] $*"
}

ok() {
  echo "[OK] $*"
}

is_positive_int() {
  [[ "${1:-}" =~ ^[1-9][0-9]*$ ]]
}

expand_path() {
  local path="$1"
  case "$path" in
    "~") printf '%s\n' "$HOME" ;;
    "~/"*) printf '%s/%s\n' "$HOME" "${path#~/}" ;;
    *) printf '%s\n' "$path" ;;
  esac
}

absolute_path() {
  local path
  path="$(expand_path "$1")"
  case "$path" in
    /*) printf '%s\n' "$path" ;;
    *) printf '%s/%s\n' "$(pwd -P)" "$path" ;;
  esac
}

detect_rc_file() {
  if [[ -n "$RC_FILE" ]]; then
    RC_FILE="$(absolute_path "$RC_FILE")"
    return
  fi

  case "${SHELL:-}" in
    */zsh) RC_FILE="${ZDOTDIR:-$HOME}/.zshrc" ;;
    */bash)
      if [[ "$(uname -s)" == "Darwin" ]]; then
        RC_FILE="$HOME/.bash_profile"
      else
        RC_FILE="$HOME/.bashrc"
      fi
      ;;
    *) RC_FILE="$HOME/.profile" ;;
  esac
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -n|--count)
        [[ $# -ge 2 ]] || die "$1 requires a value"
        COUNT="$2"
        shift 2
        ;;
      -p|--prefix)
        [[ $# -ge 2 ]] || die "$1 requires a value"
        PREFIX="$2"
        shift 2
        ;;
      -d|--dir)
        [[ $# -ge 2 ]] || die "$1 requires a value"
        BASE_DIR="$(expand_path "$2")"
        shift 2
        ;;
      --rc)
        [[ $# -ge 2 ]] || die "$1 requires a value"
        RC_FILE="$2"
        shift 2
        ;;
      --no-rc)
        WRITE_RC=0
        shift
        ;;
      --copy-shared)
        COPY_SHARED=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "Unknown option: $1"
        ;;
    esac
  done

  is_positive_int "$COUNT" || die "--count must be a positive integer"
  [[ "$PREFIX" =~ ^[A-Za-z0-9_-]+$ ]] || die "--prefix may only contain letters, numbers, '_' and '-'"
}

create_account_dirs() {
  note "Creating $COUNT Codex account slot(s) in $BASE_DIR"
  mkdir -p "$BASE_DIR"
  chmod 700 "$BASE_DIR" 2>/dev/null || true

  local i slot
  for ((i = 1; i <= COUNT; i++)); do
    slot="$BASE_DIR/${PREFIX}${i}"
    mkdir -p "$slot"
    chmod 700 "$slot" 2>/dev/null || true
  done
}

copy_shared_files() {
  [[ "$COPY_SHARED" -eq 1 ]] || return 0

  local source_home="$HOME/.codex"
  [[ -d "$source_home" ]] || {
    note "Skipping --copy-shared because ~/.codex does not exist"
    return 0
  }

  local shared_paths=(
    "rules"
    "AGENTS.md"
    "config.toml"
    "skills"
    "memories"
    "automations"
  )

  note "Copying safe shared files from ~/.codex into each slot"
  local i p src dst
  for ((i = 1; i <= COUNT; i++)); do
    for p in "${shared_paths[@]}"; do
      src="$source_home/$p"
      dst="$BASE_DIR/${PREFIX}${i}/$p"
      if [[ -e "$src" ]]; then
        rm -rf "$dst"
        cp -R "$src" "$dst"
      fi
    done
  done
}

remove_existing_block() {
  local file="$1"
  local tmp

  [[ -f "$file" ]] || return 0
  tmp="$(mktemp)"
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == begin { skip = 1; next }
    $0 == end { skip = 0; next }
    skip != 1 { print }
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
}

append_shell_block() {
  [[ "$WRITE_RC" -eq 1 ]] || return 0

  detect_rc_file
  mkdir -p "$(dirname "$RC_FILE")"
  touch "$RC_FILE"

  note "Installing shell helpers into $RC_FILE"
  remove_existing_block "$RC_FILE"

  {
    printf '\n%s\n' "$BEGIN_MARKER"
    printf '# Generated by multiple-codex-accounts/install.sh\n'
    printf 'export CODEX_ACCOUNTS_DIR="${CODEX_ACCOUNTS_DIR:-%s}"\n' "$BASE_DIR"
    printf '\n'
    printf 'codex-acc() {\n'
    printf '  local slot="${1:-}"\n'
    printf '  if [[ -z "$slot" ]]; then\n'
    printf '    echo "Usage: codex-acc <number> [codex args...]" >&2\n'
    printf '    return 2\n'
    printf '  fi\n'
    printf '  shift\n'
    printf '  CODEX_HOME="$CODEX_ACCOUNTS_DIR/%s${slot}" codex "$@"\n' "$PREFIX"
    printf '}\n'
    printf '\n'
    printf 'mca-status() {\n'
    printf '  local i\n'
    printf '  for i in'
    local i
    for ((i = 1; i <= COUNT; i++)); do
      printf ' %s' "$i"
    done
    printf '; do\n'
    printf '    printf "%s%%s: " "$i"\n' "$PREFIX"
    printf '    CODEX_HOME="$CODEX_ACCOUNTS_DIR/%s${i}" codex login status 2>&1 | sed -n "1p" || true\n' "$PREFIX"
    printf '  done\n'
    printf '}\n'
    printf '\n'
    for ((i = 1; i <= COUNT; i++)); do
      printf "alias codex-%s%s='CODEX_HOME=\"\$CODEX_ACCOUNTS_DIR/%s%s\" codex'\n" "$PREFIX" "$i" "$PREFIX" "$i"
    done
    printf '%s\n' "$END_MARKER"
  } >> "$RC_FILE"
}

print_next_steps() {
  ok "Installed $COUNT Codex account slot(s)."

  if [[ "$WRITE_RC" -eq 1 ]]; then
    cat <<EOF

Next steps:
  source "$RC_FILE"
  codex-${PREFIX}1 login
  codex-${PREFIX}2 login
  mca-status

Run Codex with a slot:
  codex-${PREFIX}1
  codex-${PREFIX}2

Or use the generic helper:
  codex-acc 1 login
  codex-acc 1
EOF
  else
    cat <<EOF

Next steps:
  CODEX_HOME="$BASE_DIR/${PREFIX}1" codex login
  CODEX_HOME="$BASE_DIR/${PREFIX}1" codex
EOF
  fi
}

main() {
  parse_args "$@"
  BASE_DIR="$(absolute_path "$BASE_DIR")"
  create_account_dirs
  BASE_DIR="$(cd "$BASE_DIR" && pwd -P)"
  copy_shared_files
  append_shell_block
  print_next_steps
}

main "$@"
